client_id = "b323444b85e59301f81c74e556dd7efe"
name = "SunsetBot"
handle = "sunsetbot"
application_url = "https://sunsetbot-production.up.railway.app"
embedded = false

[access_scopes]
scopes = "read_products,write_products,read_orders,read_customers"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://sunsetbot-production.up.railway.app/shopify/callback"
]

[webhooks]
api_version = "2024-10"

  [webhooks.subscriptions]

[[webhooks.subscriptions]]
topics = ["products/create", "products/update", "products/delete", "app/uninstalled"]
uri = "https://sunsetbot-production.up.railway.app/shopify/webhooks"
